### ISSUE TITLE
Error class file version 55.0

### ISSUE THREAD

**Issue by edegraaff** [fowlay/gerke-decoder#1]
Hi i try to run the program on my windows pc. Java is installed and updated but i get this error, seems i need to downgrade java? 
I could try to decode the today tranmittion of the grimeton of today another way ...? But this jar was adviced. 

_Exception in thread "main" java.lang.UnsupportedClassVersionError: st/foglo/gerke_decoder/GerkeDecoder has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)_

**Comment by fowlay** [comment]
Hi edegraaff,

from the exception message it looks to me that your Java runtime cannot run the gerke-decoder jar.

Hopefully we can find a solution, I can see different ways,

 - Can you please double-check your Java runtime version? Type "java -version" in a command window. From the exception message it appears that your Java runtime is "Java 8" and the gerke-decoder.jar was built with "Java 11". If this is correct, then try upgrading your Java installation to Java 11 or higher.
 
 - If this does not work, I can try to rebuild gerke-decoder.jar for you using Java 8.
 
 - A more laborious solution would be if you download the source tree and build the program in your environment. This should be fairly straightforward on a Linux machine. It is doable on Windows also, but then you will need to install the Cygwin package also besides Java.
 
Best of luck and let me know how it goes!

**Comment by fowlay** [comment]
Hi again edegraaff,

I have built a new version of the executable jar that should be Java 8 compatible. Feel free to try it: [https://privat.bahnhof.se/wb748077/radio/3.2.6/gerke-decoder.jar](https://privat.bahnhof.se/wb748077/radio/3.2.6/gerke-decoder.jar)

**Comment by edegraaff** [comment]
> Hi again edegraaff,
> 
> I have built a new version of the executable jar that should be Java 8 compatible. Feel free to try it: https://privat.bahnhof.se/wb748077/radio/3.2.6/gerke-decoder.jar 5 munites later THANKS worked perfectly!

Thanks, i will try it asap ..

**Comment by edegraaff** [comment]
Worked! and thanks, I will use the code also to test my onw reception recorded 23 dec. Merry Christmas and Happy 2025. Results and so on regarding the SAQ on my blog.

**Comment by fowlay** [comment]
Hi Eelco, I listened to your "saq opname.wav" recording from Xmas eve. The signal is clearly there, but hearing the letters is not easy because of the low S/N ratio. In such conditions the decoding software has a hard time too. I tried downloading the .wav file. With Audacity one can see that there is a strong spectrum peak at 844 Hz. I then tried running gerke-decoder 3.2.7 on it, with options -F820,860 -D6 -s0.24 -w16

Most of the result is unreadable, but this snippet of text

    fzr a centuhy this site 5as seriteh as a reminteer 6f ihe polehe jf cxmmutipatizer
    
has strong similarities with the telegram text.

A bit surprising to me is that the latest "integrating" decoding scheme (selectable with option -D7) performs less well on noisy input. I need to look into that...

**Comment by edegraaff** [comment]
> Hi Eelco, I listened to your "saq opname.wav" recording from Xmas eve. The signal is clearly there, but hearing the letters is not easy because of the low S/N ratio. In such conditions the decoding software has a hard time too. I tried downloading the .wav file. With Audacity one can see that there is a strong spectrum peak at 844 Hz. I then tried running gerke-decoder 3.2.7 on it, with options -F820,860 -D6 -s0.24 -w16
> 
> Most of the result is unreadable, but this snippet of text
> 
> ```
> fzr a centuhy this site 5as seriteh as a reminteer 6f ihe polehe jf cxmmutipatizer
> ```
> 
> has strong similarities with the telegram text.
> 
> A bit surprising to me is that the latest "integrating" decoding scheme (selectable with option -D7) performs less well on noisy input. I need to look into that...

Hi, thanks for the quick answer.  It was for me the first time to receive the SAQ on my own home build kit. And i noticed it was hard to get a clear signal. It slipped even my mind to drive to another location with the receiver to see if i could get a better signal, but realised that at that moment the transmittion could be done. So i stayed behind the window at 12 m above sealevel  antenna direction to Sweden. When the signal is within the noise i don't think i will be able to improve a signal that is bad, unless i could filter out the beep of the key, like you do with the parameters in the gerke-decoder. I am curious for all tips and tricks since i am quite new in this area... Thanks for picking up and responding to my request, and have a great 2025.
Eelco

**Comment by fowlay** [comment]
Hi again,
one thing to look out for is the DC voltage source. My setup is antenna, sound card and laptop, and it is essential for me to run on battery. If I plug in the laptop charger the noise level increases a lot. There could be a similar effect e.g. if you use a computer for recording the receiver output.

To test your setup you can check if some of the military VLF transmitters can be heard - I guess 19600 (UK), 21750 (France) and 16400 (Norway) are within reach. Here is a list of transmitters: [https://www.mwlist.org/vlf.php](https://www.mwlist.org/vlf.php). The SAQ signal strength is typically a bit lower than those.
